CI install Celerity and build examples against installed version

diff --git a/.github/workflows/celerity_ci.yml b/.github/workflows/celerity_ci.yml
--- a/.github/workflows/celerity_ci.yml
+++ b/.github/workflows/celerity_ci.yml
@@ -47,6 +47,7 @@ jobs:
       build-name: ${{ matrix.platform }}-${{ matrix.sycl-version }}-${{ matrix.build-type }}
       container-workspace: /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
       build-dir: /root/build
+      examples-build-dir: /root/build-examples
     container:
       image: build/celerity/${{ matrix.sycl-version }}
       volumes:
@@ -64,14 +65,16 @@ jobs:
       - uses: actions/checkout@v2
         with:
           submodules: true
-      - name: Run build script
-        run: bash -c "set -o pipefail; bash /root/build-celerity.sh ${{ env.container-workspace }} --build-type ${{ matrix.build-type }} 2>&1 | tee ${{ env.build-name }}.log"
+      - name: Build and install Celerity
+        run: bash -o pipefail -c "bash /root/build-celerity.sh ${{ env.container-workspace }} --build-type ${{ matrix.build-type }} --target install 2>&1 | tee ${{ env.build-name }}.log"
       # Upload build log for report step
-      - name: Upload build log
+      - name: Upload build logs
         uses: actions/upload-artifact@v1
         with:
           name: ${{ env.build-name }}
           path: ${{ env.build-name }}.log
+      - name: Build examples against installed Celerity
+        run: bash /root/build-examples.sh ${{ env.container-workspace }}/examples --build-type ${{ matrix.build-type }}
       - name: Run unit tests
         timeout-minutes: 5
         working-directory: ${{ env.build-dir }}
@@ -79,7 +82,8 @@ jobs:
         run: find test -maxdepth 1 -executable -type f -print0 | xargs -0 -n1 bash -c
       - name: Run integration tests
         timeout-minutes: 5
-        working-directory: ${{ env.build-dir }}
+        # We build examples twice, but only run the installed version (which probably has more failure modes)
+        working-directory: ${{ env.examples-build-dir }}
         run: ${{ env.container-workspace }}/ci/run-integration-tests.sh /data/Lenna.png 1 2 4
       - name: Run system tests
         working-directory: ${{ env.build-dir }}
